version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: cammoss-postgres
    environment:
      POSTGRES_DB: cammossleague
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../src/main/resources/schema-postgresql.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ../src/main/resources/data.sql:/docker-entrypoint-initdb.d/02-data.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: ..
    container_name: cammoss-app
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/cammossleague
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      JPA_DDL_AUTO: update
      JPA_SHOW_SQL: false
      SQL_INIT_MODE: always
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  postgres_data:
    driver: local